FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --omit=dev

# Copy app code
COPY . .

# Build
RUN npm run build

# Expose port
EXPOSE 3000

# Run preview server
CMD ["npm", "run", "preview"]